[package]
name = "todolang"
version = "0.1.0"
edition = "2021"

[dependencies]
internment = "0.7.0"
restore_macros = { path = "./restore_macros" }
thiserror = "1"
enum_macros = { path = "./enum_macros" }

[dev-dependencies]
pretty_assertions = "1.3"
