[package]
name = "todolang"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
derive_more = "0.99"
internment = "0.7.0"
restore_macros = { path = "./restore_macros" }
thiserror = "1"

[dev-dependencies]
pretty_assertions = "1.3"
