pub mod declaration_environment;
pub mod diagnostics;
pub mod interpreter;
pub mod lexer;
mod name_resolver;
pub mod parser;
pub mod resolver;
pub mod semantic_analyzer;
pub mod source_location;
pub mod symbol_table;
pub mod syntax;
pub mod token;
pub mod types;
